### PR TITLE
Placeholder for initial chart idea

### PR DESCRIPTION
**Pull request by somewes**

### CODE REVIEW

**Comment by somewes** [comment]
@jaredlewis look at the year

**Comment by jaredlewis** [comment]
@wesokes lets get this merged ASAP

**Comment by somewes** [comment]
what a great project @jaredlewis

**Comment by somewes** [comment]
@jaredlewis still waiting on review here

**Review by jaredlewis — APPROVED** [review]

**Comment by somewes** [comment]
let's get this thing goin!

**Pull request merged**
